[project]
name = "payment-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mrKazzila", email = "mrkazzila@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
payment-processing = "payment_processing:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
